export interface Country {
  code: string;
  name: string;
  language: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', language: 'en' },
  { code: 'ZA', name: 'Afrique du Sud', language: 'en' },
  { code: 'AL', name: 'Albanie', language: 'en' },
  { code: 'DZ', name: 'Algérie', language: 'fr' },
  { code: 'DE', name: 'Allemagne', language: 'en' },
  { code: 'AD', name: 'Andorre', language: 'en' },
  { code: 'AO', name: 'Angola', language: 'fr' },
  { code: 'AG', name: 'Antigua-et-Barbuda', language: 'en' },
  { code: 'SA', name: 'Arabie saoudite', language: 'en' },
  { code: 'AR', name: 'Argentine', language: 'en' },
  { code: 'AM', name: 'Arménie', language: 'en' },
  { code: 'AU', name: 'Australie', language: 'en' },
  { code: 'AT', name: 'Autriche', language: 'en' },
  { code: 'AZ', name: 'Azerbaïdjan', language: 'en' },
  { code: 'BS', name: 'Bahamas', language: 'en' },
  { code: 'BH', name: 'Bahreïn', language: 'en' },
  { code: 'BD', name: 'Bangladesh', language: 'en' },
  { code: 'BB', name: 'Barbade', language: 'en' },
  { code: 'BE', name: 'Belgique', language: 'fr' },
  { code: 'BZ', name: 'Belize', language: 'en' },
  { code: 'BJ', name: 'Bénin', language: 'fr' },
  { code: 'BT', name: 'Bhoutan', language: 'en' },
  { code: 'BY', name: 'Biélorussie', language: 'en' },
  { code: 'MM', name: 'Birmanie', language: 'en' },
  { code: 'BO', name: 'Bolivie', language: 'en' },
  { code: 'BA', name: 'Bosnie-Herzégovine', language: 'en' },
  { code: 'BW', name: 'Botswana', language: 'en' },
  { code: 'BR', name: 'Brésil', language: 'en' },
  { code: 'BN', name: 'Brunei', language: 'en' },
  { code: 'BG', name: 'Bulgarie', language: 'en' },
  { code: 'BF', name: 'Burkina Faso', language: 'fr' },
  { code: 'BI', name: 'Burundi', language: 'fr' },
  { code: 'KH', name: 'Cambodge', language: 'en' },
  { code: 'CM', name: 'Cameroun', language: 'fr' },
  { code: 'CA', name: 'Canada', language: 'fr' },
  { code: 'CV', name: 'Cap-Vert', language: 'fr' },
  { code: 'CF', name: 'République centrafricaine', language: 'fr' },
  { code: 'CL', name: 'Chili', language: 'en' },
  { code: 'CN', name: 'Chine', language: 'en' },
  { code: 'CY', name: 'Chypre', language: 'en' },
  { code: 'CO', name: 'Colombie', language: 'en' },
  { code: 'KM', name: 'Comores', language: 'fr' },
  { code: 'CG', name: 'Congo-Brazzaville', language: 'fr' },
  { code: 'CD', name: 'Congo-Kinshasa', language: 'fr' },
  { code: 'KP', name: 'Corée du Nord', language: 'en' },
  { code: 'KR', name: 'Corée du Sud', language: 'en' },
  { code: 'CR', name: 'Costa Rica', language: 'en' },
  { code: 'CI', name: "Côte d'Ivoire", language: 'fr' },
  { code: 'HR', name: 'Croatie', language: 'en' },
  { code: 'CU', name: 'Cuba', language: 'en' },
  { code: 'DK', name: 'Danemark', language: 'en' },
  { code: 'DJ', name: 'Djibouti', language: 'fr' },
  { code: 'DM', name: 'Dominique', language: 'en' },
  { code: 'EG', name: 'Égypte', language: 'en' },
  { code: 'AE', name: 'Émirats arabes unis', language: 'en' },
  { code: 'EC', name: 'Équateur', language: 'en' },
  { code: 'ER', name: 'Érythrée', language: 'en' },
  { code: 'ES', name: 'Espagne', language: 'en' },
  { code: 'EE', name: 'Estonie', language: 'en' },
  { code: 'US', name: 'États-Unis', language: 'en' },
  { code: 'ET', name: 'Éthiopie', language: 'en' },
  { code: 'FJ', name: 'Fidji', language: 'en' },
  { code: 'FI', name: 'Finlande', language: 'en' },
  { code: 'FR', name: 'France', language: 'fr' },
  { code: 'GA', name: 'Gabon', language: 'fr' },
  { code: 'GM', name: 'Gambie', language: 'en' },
  { code: 'GE', name: 'Géorgie', language: 'en' },
  { code: 'GH', name: 'Ghana', language: 'en' },
  { code: 'GR', name: 'Grèce', language: 'en' },
  { code: 'GD', name: 'Grenade', language: 'en' },
  { code: 'GT', name: 'Guatemala', language: 'en' },
  { code: 'GN', name: 'Guinée', language: 'fr' },
  { code: 'GQ', name: 'Guinée équatoriale', language: 'fr' },
  { code: 'GW', name: 'Guinée-Bissau', language: 'fr' },
  { code: 'GY', name: 'Guyana', language: 'en' },
  { code: 'HT', name: 'Haïti', language: 'fr' },
  { code: 'HN', name: 'Honduras', language: 'en' },
  { code: 'HU', name: 'Hongrie', language: 'en' },
  { code: 'IN', name: 'Inde', language: 'en' },
  { code: 'ID', name: 'Indonésie', language: 'en' },
  { code: 'IR', name: 'Iran', language: 'en' },
  { code: 'IQ', name: 'Irak', language: 'en' },
  { code: 'IE', name: 'Irlande', language: 'en' },
  { code: 'IS', name: 'Islande', language: 'en' },
  { code: 'IL', name: 'Israël', language: 'en' },
  { code: 'IT', name: 'Italie', language: 'en' },
  { code: 'JM', name: 'Jamaïque', language: 'en' },
  { code: 'JP', name: 'Japon', language: 'en' },
  { code: 'JO', name: 'Jordanie', language: 'en' },
  { code: 'KZ', name: 'Kazakhstan', language: 'en' },
  { code: 'KE', name: 'Kenya', language: 'en' },
  { code: 'KG', name: 'Kirghizistan', language: 'en' },
  { code: 'KI', name: 'Kiribati', language: 'en' },
  { code: 'KW', name: 'Koweït', language: 'en' },
  { code: 'LA', name: 'Laos', language: 'en' },
  { code: 'LS', name: 'Lesotho', language: 'en' },
  { code: 'LV', name: 'Lettonie', language: 'en' },
  { code: 'LB', name: 'Liban', language: 'en' },
  { code: 'LR', name: 'Liberia', language: 'en' },
  { code: 'LY', name: 'Libye', language: 'en' },
  { code: 'LI', name: 'Liechtenstein', language: 'en' },
  { code: 'LT', name: 'Lituanie', language: 'en' },
  { code: 'LU', name: 'Luxembourg', language: 'fr' },
  { code: 'MK', name: 'Macédoine du Nord', language: 'en' },
  { code: 'MG', name: 'Madagascar', language: 'fr' },
  { code: 'MY', name: 'Malaisie', language: 'en' },
  { code: 'MW', name: 'Malawi', language: 'en' },
  { code: 'MV', name: 'Maldives', language: 'en' },
  { code: 'ML', name: 'Mali', language: 'fr' },
  { code: 'MT', name: 'Malte', language: 'en' },
  { code: 'MA', name: 'Maroc', language: 'fr' },
  { code: 'MH', name: 'Îles Marshall', language: 'en' },
  { code: 'MU', name: 'Maurice', language: 'fr' },
  { code: 'MR', name: 'Mauritanie', language: 'fr' },
  { code: 'MX', name: 'Mexique', language: 'en' },
  { code: 'FM', name: 'Micronésie', language: 'en' },
  { code: 'MD', name: 'Moldavie', language: 'en' },
  { code: 'MC', name: 'Monaco', language: 'fr' },
  { code: 'MN', name: 'Mongolie', language: 'en' },
  { code: 'ME', name: 'Monténégro', language: 'en' },
  { code: 'MZ', name: 'Mozambique', language: 'en' },
  { code: 'NA', name: 'Namibie', language: 'en' },
  { code: 'NR', name: 'Nauru', language: 'en' },
  { code: 'NP', name: 'Népal', language: 'en' },
  { code: 'NI', name: 'Nicaragua', language: 'en' },
  { code: 'NE', name: 'Niger', language: 'fr' },
  { code: 'NG', name: 'Nigeria', language: 'en' },
  { code: 'NO', name: 'Norvège', language: 'en' },
  { code: 'NZ', name: 'Nouvelle-Zélande', language: 'en' },
  { code: 'OM', name: 'Oman', language: 'en' },
  { code: 'UG', name: 'Ouganda', language: 'en' },
  { code: 'UZ', name: 'Ouzbékistan', language: 'en' },
  { code: 'PK', name: 'Pakistan', language: 'en' },
  { code: 'PW', name: 'Palaos', language: 'en' },
  { code: 'PA', name: 'Panama', language: 'en' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', language: 'en' },
  { code: 'PY', name: 'Paraguay', language: 'en' },
  { code: 'NL', name: 'Pays-Bas', language: 'en' },
  { code: 'PE', name: 'Pérou', language: 'en' },
  { code: 'PH', name: 'Philippines', language: 'en' },
  { code: 'PL', name: 'Pologne', language: 'en' },
  { code: 'PT', name: 'Portugal', language: 'en' },
  { code: 'QA', name: 'Qatar', language: 'en' },
  { code: 'RO', name: 'Roumanie', language: 'en' },
  { code: 'GB', name: 'Royaume-Uni', language: 'en' },
  { code: 'RU', name: 'Russie', language: 'en' },
  { code: 'RW', name: 'Rwanda', language: 'fr' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', language: 'en' },
  { code: 'SM', name: 'Saint-Marin', language: 'en' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', language: 'en' },
  { code: 'LC', name: 'Sainte-Lucie', language: 'en' },
  { code: 'SB', name: 'Îles Salomon', language: 'en' },
  { code: 'SV', name: 'Salvador', language: 'en' },
  { code: 'WS', name: 'Samoa', language: 'en' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', language: 'fr' },
  { code: 'SN', name: 'Sénégal', language: 'fr' },
  { code: 'RS', name: 'Serbie', language: 'en' },
  { code: 'SC', name: 'Seychelles', language: 'fr' },
  { code: 'SL', name: 'Sierra Leone', language: 'en' },
  { code: 'SG', name: 'Singapour', language: 'en' },
  { code: 'SK', name: 'Slovaquie', language: 'en' },
  { code: 'SI', name: 'Slovénie', language: 'en' },
  { code: 'SO', name: 'Somalie', language: 'en' },
  { code: 'SD', name: 'Soudan', language: 'en' },
  { code: 'SS', name: 'Soudan du Sud', language: 'en' },
  { code: 'LK', name: 'Sri Lanka', language: 'en' },
  { code: 'SE', name: 'Suède', language: 'en' },
  { code: 'CH', name: 'Suisse', language: 'fr' },
  { code: 'SR', name: 'Suriname', language: 'en' },
  { code: 'SY', name: 'Syrie', language: 'en' },
  { code: 'TJ', name: 'Tadjikistan', language: 'en' },
  { code: 'TZ', name: 'Tanzanie', language: 'en' },
  { code: 'TD', name: 'Tchad', language: 'fr' },
  { code: 'CZ', name: 'Tchéquie', language: 'en' },
  { code: 'TH', name: 'Thaïlande', language: 'en' },
  { code: 'TL', name: 'Timor oriental', language: 'en' },
  { code: 'TG', name: 'Togo', language: 'fr' },
  { code: 'TO', name: 'Tonga', language: 'en' },
  { code: 'TT', name: 'Trinité-et-Tobago', language: 'en' },
  { code: 'TN', name: 'Tunisie', language: 'fr' },
  { code: 'TM', name: 'Turkménistan', language: 'en' },
  { code: 'TR', name: 'Turquie', language: 'en' },
  { code: 'TV', name: 'Tuvalu', language: 'en' },
  { code: 'UA', name: 'Ukraine', language: 'en' },
  { code: 'UY', name: 'Uruguay', language: 'en' },
  { code: 'VU', name: 'Vanuatu', language: 'en' },
  { code: 'VA', name: 'Vatican', language: 'en' },
  { code: 'VE', name: 'Venezuela', language: 'en' },
  { code: 'VN', name: 'Viêt Nam', language: 'en' },
  { code: 'YE', name: 'Yémen', language: 'en' },
  { code: 'ZM', name: 'Zambie', language: 'en' },
  { code: 'ZW', name: 'Zimbabwe', language: 'en' },
];
